name: TSH_4_v3_train_dellayer128.a100
n_gpu: 2

arch:
  type: Baseline
  args:
    n_hidden: 568
    embedding_args:
      arch: roberta_large
      dropout: 0.0
      attention_dropout: 0.0
      activation_dropout: 0.0
      ffn_embed_dim: 5120
      layers: 33
      attention_heads: 20
      embed_dim: 1280
      max_positions: 1024
      learned_pos: true
      activation_fn: gelu
      use_bert_init: true
      normalize_before: true
      preact_normalize: true
      normalize_after: true
      token_dropout: true
      no_seed_provided: false
      pooler_activation_fn: 'tanh'
      pooler_dropout: 0.0
      checkpoint_transformer_block: false
      untie_weights_roberta: false
    embedding_pretrained: "/gpfs/gsfs12/users/Irp-jiang/share/yyang/ESM/checkpoints/esm2_t33_650M_UR50D.pt"

data_loader:
  type: TsvDataLoader
  args:
    path_to_tsv: "./data/train_4.tsv"
    batch_size: 50
    num_workers: 8
    shuffle: true

valid_data_loader:
  type: TsvDataLoader
  args:
    path_to_tsv: "./data/validation_4.tsv"
    batch_size: 50
    num_workers: 8
    shuffle: true

transformer:
  type: ESM2Tokenize
  args: {}

loss: cross_entropy_loss

metrics:
  - accuracy
  - recall
  - precision
  - specificity
  - f1_score
  - mcc

optimizer:
  type: Adam
  args:
    lr: 0.0005
    weight_decay: 0

lr_scheduler:
  type: StepLR
  args:
    step_size: 5
    gamma: 0.1

trainer:
  epochs: 100
  save_dir: result/
  save_period: 1
  verbosity: 2
  monitor: min val_loss
  early_stop: 3
  tensorboard: false
