name: TSH_4_v3_train
n_gpu: 2

arch:
  type: Baseline
  args:
    n_hidden: 568

data_loader:
  type: TsvDataLoader
  args:
    path_to_tsv: "./data/train_4.tsv"
    batch_size: 25
    num_workers: 8
    shuffle: true

valid_data_loader:
  type: TsvDataLoader
  args:
    path_to_tsv: "./data/validation_4.tsv"
    batch_size: 25
    num_workers: 8
    shuffle: true

transformer:
  type: SeqVecTokenize
  args:
    max_amino_acids: 2000
    weights_file: "/data/yangy34/database/uniref50_v2/weights.hdf5"
    options_file: "/data/yangy34/database/uniref50_v2/options.json"

loss: cross_entropy_loss

metrics:
  - accuracy
  - recall
  - precision
  - specificity
  - f1_score
  - mcc

optimizer:
  type: Adam
  args:
    lr: 0.0005
    weight_decay: 0

lr_scheduler:
  type: StepLR
  args:
    step_size: 5
    gamma: 0.1

trainer:
  epochs: 100
  save_dir: result/
  save_period: 1
  verbosity: 2
  monitor: min val_loss
  early_stop: 3
  tensorboard: false
